[project]
name = "facts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-community>=0.3.1",
    "langchain-openai>=0.2.1",
    "langchain-text-splitters>=0.3.0",
    "langchain>=0.3.1",
]
